/** Names of AI image generation tools/services, as they tend to appear in software/creator-tool fields. */
export const AI_GENERATOR_TERMS: readonly string[] = [
  'dall-e',
  'dalle',
  'openai',
  'chatgpt',
  'midjourney',
  'stable diffusion',
  'stablediffusion',
  'sdxl',
  'flux',
  'black forest labs',
  'comfyui',
  'automatic1111',
  'a1111',
  'invokeai',
  'leonardo',
  'ideogram',
  'firefly',
  'adobe firefly',
  'runway',
  'sora',
  'imagen',
  'gemini',
  'veo',
  'recraft',
  'krea',
  'nightcafe',
  'dreamstudio'
];
